### ISSUE TITLE
Jarchiwum a Kick

### ISSUE THREAD

**Issue by INCER212** [schriker/jar-next#23]
Kierowniku złoty, czy istnieje techniczna możliwość, aby zapisy strumieni z Kicka dało się odtwarzać z czatem za pomocą funkcji z załącznika?
![jdsc](https://github.com/user-attachments/assets/85177a89-923d-462f-a64c-b7f6153432c0)

**Comment by schriker** [comment]
@INCER212 Szybko googlujac nie widzę żeby kick udostępniał API swojego playera. Z mojej strony ten projekt jest już zamknięty, nie śledzę jadisco i wonzia już od dłuższego czasu, ale jeśli komuś się chce może dopisać taką funkcję.

**Comment by INCER212** [comment]
Dziękuję za pochylenie się nad sprawą, miłego dnia :)
